# Generated by Django 4.1 on 2022-08-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=100)),
                ('plate_type', models.CharField(max_length=100)),
                ('truck_type', models.CharField(max_length=100)),
                ('production_year', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
