# Generated by Django 4.1 on 2022-08-13 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_userz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('loading_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('license_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.truck')),
                ('shipper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.userz')),
            ],
        ),
    ]
